-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial NOT NULL,
    user_name character varying(32) NOT NULL,
    email character varying(255) NOT NULL,
    balance integer NOT NULL DEFAULT 0,
    passwordhash character varying(255) NOT NULL,
    registration_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.track
(
    track_id serial NOT NULL,
    track_title character varying(255) NOT NULL,
    length integer NOT NULL,
    date_posted timestamp without time zone NOT NULL,
    release_id integer NOT NULL,
    PRIMARY KEY (track_id)
);

CREATE TABLE IF NOT EXISTS public.artist
(
    artist_id serial NOT NULL,
    artist_name character varying(32) NOT NULL,
    PRIMARY KEY (artist_id)
);

CREATE TABLE IF NOT EXISTS public.release
(
    release_id serial NOT NULL,
    release_name character varying(32) NOT NULL,
    PRIMARY KEY (release_id)
);

CREATE TABLE IF NOT EXISTS public.artist_release
(
    junction_id serial NOT NULL,
    artist_id integer NOT NULL,
    release_id integer NOT NULL,
    PRIMARY KEY ("junction_id")
);

CREATE TABLE IF NOT EXISTS public.user_release
(
    junction_id serial NOT NULL,
    user_id integer NOT NULL,
    release_id integer NOT NULL,
    PRIMARY KEY (junction_id)
);

ALTER TABLE IF EXISTS public.track
    ADD FOREIGN KEY (release_id)
    REFERENCES public.release (release_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.artist_release
    ADD FOREIGN KEY (artist_id)
    REFERENCES public.artist (artist_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.artist_release
    ADD FOREIGN KEY (release_id)
    REFERENCES public.release (release_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_release
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_release
    ADD FOREIGN KEY (release_id)
    REFERENCES public.release (release_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;